name: prepare-mobile-build
description: Action to prepare environment for mobile build

runs:
  using: composite
  steps:
    # The required ruby version is mentioned in '.ruby-version'
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0

    - name: ci/setup-fastlane-dependencies
      shell: bash
      run: |
        echo "::group::setup-fastlane-dependencies"
        bundle install
        echo "::endgroup::"
      working-directory: ./fastlane

    - name: Cache Ruby gems
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: ci/prepare-node-deps
      uses: ./.github/actions/prepare-node-deps
